version: '3'
services:
  repeater:
    image: repeater
    container_name: repeater
    restart: unless-stopped

    environment:
      # Repeat mDNS from VLAN 30 to 10 and 20
      - MDNS=192.168.30.0:192.168.10.0,192.168.20.0
      # Proxy websocket on port 8001 and 8002 to ip 192.168.30.100
      - WS=192.168.30.100:8001,8002
      
    networks:
      #- default
      vlan30:
        ipv4_address: 192.168.30.200
      vlan20:
        ipv4_address: 192.168.20.200
      vlan10:
        ipv4_address: 192.168.10.200

networks:
  vlan30:
    name: vlan30
    driver: macvlan
    driver_opts:
      parent: eth0.30
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.1 
  vlan20:
    name: vlan20
    driver: macvlan
    driver_opts:
      parent: eth0.20
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1 
  vlan10:
    name: vlan10
    driver: macvlan
    driver_opts:
      parent: eth0.10
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1 